#node image
FROM node:18-alpine AS base

RUN mkdir /home/node/frontend && chown -R node:node /home/node/frontend

FROM base AS dependencies

WORKDIR /home/node/frontend

COPY package*.json ./

RUN npm install

FROM base as dev

WORKDIR /home/node/frontend

COPY --chown=node:node . .

# Expose port 3000
EXPOSE 3000

RUN npm install next -g

# Start the app
CMD ["npm", "run", "dev"]
# FROM node:18-alpine

# WORKDIR /app

# COPY package.json ./

# RUN npm install

# COPY . .

# CMD ["npm", "run", "dev"]