version: "3.1"
services:
  leetcode-checkin-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/home/node/backend
      - /home/node/backend/node_modules
  leetcode-checkin-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/node/frontend
      - /home/node/frontend/node_modules
    depends_on:
      - leetcode-checkin-backend
